/**
 * Timezone options aligned with Master-Service TimezoneEnum.
 * Enum name (e.g. ASIA_KATHMANDU) is sent to API; display (e.g. Asia/Kathmandu) is shown in UI.
 */

/** Convert backend enum name to display string (e.g. ASIA_KATHMANDU -> Asia/Kathmandu) */
export function formatTimezoneDisplay(enumName: string): string {
  if (!enumName || typeof enumName !== 'string') return enumName;
  if (enumName.includes('/')) return enumName; // already display form
  return enumName
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('/');
}

/** Timezone enum constant names for dropdown (subset; extend to match backend TimezoneEnum) */
export const TIMEZONE_ENUM_NAMES: string[] = [
  'AFRICA_ABIDJAN', 'AFRICA_ACCRA', 'AFRICA_CAIRO', 'AFRICA_JOHANNESBURG', 'AFRICA_LAGOS', 'AFRICA_NAIROBI', 'AFRICA_TUNIS',
  'AMERICA_ANCHORAGE', 'AMERICA_ARGENTINA_BUENOS_AIRES', 'AMERICA_BOGOTA', 'AMERICA_CARACAS', 'AMERICA_CHICAGO', 'AMERICA_COSTA_RICA',
  'AMERICA_DENVER', 'AMERICA_DETROIT', 'AMERICA_EL_SALVADOR', 'AMERICA_GUATEMALA', 'AMERICA_HALIFAX', 'AMERICA_LA_PAZ', 'AMERICA_LIMA',
  'AMERICA_LOS_ANGELES', 'AMERICA_MEXICO_CITY', 'AMERICA_MONTEVIDEO', 'AMERICA_NEW_YORK', 'AMERICA_PANAMA', 'AMERICA_PHOENIX',
  'AMERICA_PUERTO_RICO', 'AMERICA_SANTIAGO', 'AMERICA_SAO_PAULO', 'AMERICA_TORONTO', 'AMERICA_VANCOUVER', 'AMERICA_WINNIPEG',
  'ASIA_AMMAN', 'ASIA_BAGHDAD', 'ASIA_BAHRAIN', 'ASIA_BANGKOK', 'ASIA_BEIRUT', 'ASIA_COLOMBO', 'ASIA_DHAKA', 'ASIA_DUBAI',
  'ASIA_HO_CHI_MINH', 'ASIA_HONG_KONG', 'ASIA_JAKARTA', 'ASIA_JERUSALEM', 'ASIA_KABUL', 'ASIA_KARACHI', 'ASIA_KATHMANDU', 'ASIA_KOLKATA',
  'ASIA_KUALA_LUMPUR', 'ASIA_KUWAIT', 'ASIA_MANILA', 'ASIA_MUSCAT', 'ASIA_QATAR', 'ASIA_RIYADH', 'ASIA_SEOUL', 'ASIA_SHANGHAI',
  'ASIA_SINGAPORE', 'ASIA_TAIPEI', 'ASIA_TEHRAN', 'ASIA_TOKYO', 'ASIA_YANGON', 'ASIA_YEREVAN',
  'ATLANTIC_AZORES', 'ATLANTIC_CAPE_VERDE', 'ATLANTIC_REYKJAVIK',
  'AUSTRALIA_ADELAIDE', 'AUSTRALIA_BRISBANE', 'AUSTRALIA_DARWIN', 'AUSTRALIA_MELBOURNE', 'AUSTRALIA_PERTH', 'AUSTRALIA_SYDNEY',
  'EUROPE_AMSTERDAM', 'EUROPE_ATHENS', 'EUROPE_BERLIN', 'EUROPE_BRUSSELS', 'EUROPE_BUCHAREST', 'EUROPE_BUDAPEST', 'EUROPE_COPENHAGEN',
  'EUROPE_DUBLIN', 'EUROPE_HELSINKI', 'EUROPE_ISTANBUL', 'EUROPE_LISBON', 'EUROPE_LONDON', 'EUROPE_MADRID', 'EUROPE_MINSK', 'EUROPE_MOSCOW',
  'EUROPE_OSLO', 'EUROPE_PARIS', 'EUROPE_PRAGUE', 'EUROPE_RIGA', 'EUROPE_ROME', 'EUROPE_SOFIA', 'EUROPE_STOCKHOLM', 'EUROPE_TALLINN',
  'EUROPE_VIENNA', 'EUROPE_WARSAW', 'EUROPE_ZURICH',
  'INDIAN_MALDIVES', 'INDIAN_MAURITIUS',
  'PACIFIC_AUCKLAND', 'PACIFIC_FIJI', 'PACIFIC_GUAM', 'PACIFIC_HONOLULU', 'PACIFIC_NOUMEA', 'PACIFIC_PORT_MORESBY',
];

/** Options for select: { value: enum name, label: display } */
export const TIMEZONE_OPTIONS = TIMEZONE_ENUM_NAMES.map((value) => ({
  value,
  label: formatTimezoneDisplay(value),
}));
